### ISSUE TITLE
onMessage Exception

### ISSUE THREAD

**Issue by zhangyongjiang** [ably/ably-java#1009]
Stack Trace:

(ERROR): io.ably.lib.transport.WebSocketTransport: Unexpected exception processing received binary message
io.ably.lib.types.AblyException: java.lang.IndexOutOfBoundsException: toIndex = 9
	at io.ably.lib.types.AblyException.fromThrowable(AblyException.java:54)
	at io.ably.lib.transport.ConnectionManager.onMessage(ConnectionManager.java:1187)
	at io.ably.lib.transport.WebSocketTransport.receive(WebSocketTransport.java:104)
	at io.ably.lib.transport.WebSocketTransport$WsClient.onMessage(WebSocketTransport.java:198)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:641)
	at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:959)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:912)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 9
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at io.ably.lib.transport.ConnectionManager$PendingMessageQueue.ack(ConnectionManager.java:1698)
	at io.ably.lib.transport.ConnectionManager.onAck(ConnectionManager.java:1318)
	at io.ably.lib.transport.ConnectionManager.onMessage(ConnectionManager.java:1173)
	... 9 more

![](https://github.com/ably/ably-java/assets/1043451/01966d65-6f62-46ff-b40f-fae4e6f07f3d)

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/ECO-4813) by [Unito](https://www.unito.io)

**Comment by zhangyongjiang** [comment]
@lawrence-forooghian 
Yes, we are using ably-java 1.2.38. 
I cannot reproduce the bug always. You may try these steps back and forth. 
1. create few ably realtime instances, 
2. for each ably realtime instance
- wait for connected
- subscribe to a channel for each instance. 
- use a thread to publish messages to the channel every 10 seconds
6. disconnect the network (turn off wife) for **few minutes** 
7. turn on network, wait for couple minutes
8. repeat step 6 and 7

**Comment by ttypic** [comment]
Hey @zhangyongjiang,

We have released version `1.2.39` of `ably-java`, which includes a fix for the reported issue. If you continue to experience the problem after updating, please feel free to reopen the issue.
