### ISSUE TITLE
HTTP Version Not Supported

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#124]
When running https://github.com/ably/demo-mobile-android on a physical Android device, it crashes with the following error.

I suspect this is an ably-java issue as opposed to an Android Demo issue.

```
04-01 12:11:25.676 25098-25098/com.ablydemo I/System.out: (INFO): io.ably.lib.realtime.AblyRealtime: started
04-01 12:11:25.676 25098-25098/com.ablydemo I/System.out: (INFO): Auth(): using token auth with authUrl
04-01 12:11:25.683 25098-25098/com.ablydemo I/System.out: (VERBOSE): io.ably.lib.transport.ConnectionManager: requestState(): requesting connecting; id = null
04-01 12:11:25.684 25098-25699/com.ablydemo I/System.out: (VERBOSE): io.ably.lib.transport.ConnectionManager: notifyState(): notifying connecting; id = null
04-01 12:11:25.688 25098-25699/com.ablydemo I/System.out: (INFO): TokenAuth.authorise(): 
04-01 12:11:25.688 25098-25699/com.ablydemo I/System.out: (INFO): TokenAuth.authorise(): requesting new token
04-01 12:11:25.689 25098-25699/com.ablydemo I/System.out: (INFO): Auth.requestToken(): using token auth with auth_url
04-01 12:11:26.376 25098-25699/com.ablydemo I/System.out: (ERROR): io.ably.lib.http.Http: Error response from server: statusCode = 505; statusLine = HTTP Version Not Supported
04-01 12:11:26.376 25098-25699/com.ablydemo I/System.out: (ERROR): io.ably.lib.transport.WebSocketTransport: Unexpected exception attempting connection; wsUri = wss://realtime.ably.io:443/
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out: io.ably.lib.types.AblyException: java.lang.Exception: HTTP Version Not Supported
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.http.Http.httpExecute(Http.java:383)
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.http.Http.getUri(Http.java:194)
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.requestToken(Auth.java:381)
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.http.TokenAuth.authorise(TokenAuth.java:54)
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.authorise(Auth.java:325)
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.getAuthParams(Auth.java:539)
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.transport.WebSocketTransport.connect(WebSocketTransport.java:59)
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.connectImpl(ConnectionManager.java:614)
04-01 12:11:26.377 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.handleStateRequest(ConnectionManager.java:421)
04-01 12:11:26.378 25098-25699/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.run(ConnectionManager.java:529)
04-01 12:11:26.378 25098-25699/com.ablydemo I/System.out:     at java.lang.Thread.run(Thread.java:818)
04-01 12:11:26.378 25098-25699/com.ablydemo I/System.out: Caused by: java.lang.Exception: HTTP Version Not Supported
04-01 12:11:26.378 25098-25699/com.ablydemo I/System.out: 	... 11 more
```

**Comment by mattheworiordan** [comment]
FYI. the device I tried it on is a OnePule ONE E1001 Android 5.1.1, API 22

**Comment by mattheworiordan** [comment]
It also fails on an emulator now with the same error

**Comment by paddybyers** [comment]
We should check that the URL is valid: http://stackoverflow.com/a/14292195
