### ISSUE TITLE
Unable to deploy client lib in Android Studio project on OSX

### ISSUE THREAD

**Issue by stannedelchev** [ably/ably-java#39]
1. git clone ably/ably-java
2. cd to ably-java
3. `ant clean && ant`
4. Create new Android project via `Blank Activity` template
5. Copy ably-android.jar and ably.jar into Android project folder/app/libs
6. Set up Android Studio project to depend on `ably-android.jar` via the Settings Dialog
7. Make project -> make completes successfully
8. Run -> Debug 'app' -> gradle breaks with exception:

```
Information:Gradle tasks [:app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.android.dx.command.dexer.Main.processClass(Main.java:752)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:672)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
	at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
	at com.android.dx.command.dexer.Main.processClass(Main.java:749)
	... 12 more
1 error; aborting
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 0.667 secs
Information:1 error
Information:0 warnings
Information:See complete output in console
```

Android Studio:
<img width="399" alt="screen shot 2015-08-25 at 1 44 43 pm" src="https://cloud.githubusercontent.com/assets/590590/9464803/84d242c8-4b2f-11e5-8bfc-24e275596649.png">

```
Stans-MBP:ably-java stan$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

Stans-MBP:ably-java stan$ ant -version
Apache Ant(TM) version 1.9.4 compiled on April 29 2014

```

**Comment by mattheworiordan** [comment]
@paddybyers can to help?

**Comment by paddybyers** [comment]
What JDK version do you have? I'm guessing Java8 so by default it's building class files with java bytecode version 52, whereas a maximum of 51 is supported on Android.

Can you confirm that adding:

    source="1.6" target="1.6"

attributes to the `javac` task in `build.xml` resolves it?

**Comment by stannedelchev** [comment]
Yes,  version is `1.8.0_40`. so building in 1.6 fixed it, thanks!

**Comment by mattheworiordan** [comment]
@paddybyers can you add a note to the README about this and close?

**Comment by paddybyers** [comment]
> can you add a note to the README

I think we should just apply that change. @stannedelchev can you do a PR?

**Comment by stannedelchev** [comment]
Sure, I'll do one tomorrow. Would you like to split the `compile` task, so that we target 1.6 only on Android, or is 1.6 fine for any platform?

**Comment by paddybyers** [comment]
I think ideally for JRE we'd default to the current java version, with 1.6 for Android. Then of course we have the question of how to specify a non-default version for JRE....

**Comment by stannedelchev** [comment]
OK, added PR #42 .
I'm not really familiar with Ant specifics, but IMO it should be possible to specify the version via a command-line parameter?
That way the user can do something like
`ant clean && ant build --version=1.6` if he requires a custom version, or just
`ant clean && ant build` in order to build with the default/current JDK.

**Comment by paddybyers** [comment]
> That way the user can do something like
> ant clean && ant build --version=1.6 if he requires a custom version

In fact you can:

    -Dant.build.javac.target=1.6

**Comment by mattheworiordan** [comment]
Is this still an issue?

**Comment by paddybyers** [comment]
> Is this still an issue?

I don't believe so; I have been testing on OSX with Java 8.

**Comment by mattheworiordan** [comment]
@stannedelchev can you confirm so that we can close this issue?

**Comment by stannedelchev** [comment]
I'll test it today from `master` and close the issue if everything is OK.

**Comment by stannedelchev** [comment]
Closing the issue. Running `./gradlew fullJar` in `master` outputs the library correctly and works fine in Android Studio.
