### ISSUE TITLE
"Attempt to invoke virtual method 'int io.ably.lib.types.ProtocolMessage$Action.ordinal()' on a null object reference"

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-java#398]
From [customer](https://app.intercom.io/a/apps/ua39m1ld/inbox/inbox/all/conversations/17110405694)
```
io.ably.lib.transport.WebSocketTransport: Unexpected exception processing received binary message
io.ably.lib.types.AblyException: java.lang.NullPointerException: Attempt to invoke virtual method 'int io.ably.lib.types.ProtocolMessage$Action.ordinal()' on a null object reference
06-22 16:13:06.118 2697-6111/? I/System.out: at io.ably.lib.transport.ConnectionManager.onMessage(ConnectionManager.java:494)
at io.ably.lib.transport.WebSocketTransport$WsClient.onMessage(WebSocketTransport.java:164)
at org.a.a.a.onWebsocketMessage(WebSocketClient.java:253)
at org.a.c.b(WebSocketImpl.java:381)
at org.a.a.a.run(WebSocketClient.java:3158)
at java.lang.Thread.run(Thread.java:760)
```
They say they are on 1.0.1, and would take them a while to upgrade to 1.0.3 to see if it still occurs on that. I've asked them to try anyway, but in the meantime filing this issue in case it's obvious if the issue either has or hasn't been fixed in 1.0.3.

**Comment by SimonWoolf** [comment]
Customer says they can no longer reproduce on 1.0.3.
