### ISSUE TITLE
java.lang.NoClassDefFoundError: org/msgpack/value/Value

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#460]
Customer reporting an issue following an upgrade to 1.1.

```
java.lang.NoClassDefFoundError: org/msgpack/value/Value
at io.ably.lib.rest.Auth$TokenRequest.asJsonElement(Auth.java:438)
at io.ably.lib.rest.Auth.requestToken(Auth.java:683)
```

**Comment by paddybyers** [comment]
This is resolved by https://github.com/ably/ably-java/commit/7284a0478eace6206f5f3b2a50c556a56cfacff2
