### ISSUE TITLE
After loss of connectivity, and transport closure due to timeout, the ConnectionManager still thinks the transport is active

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#495]
An extract from a log:

```
[Ably internal] Unexpected exception in WsClient Exception: java.net.UnknownHostException: realtime.ably.io

[Ably internal] Unexpected exception attempting connection; wsUri = wss://realtime.ably.io:443/ Exception: io.ably.lib.types.AblyException: io.ably.lib.types.AblyException$HostFailedException: java.net.UnknownHostException: <redacted>
[Ably internal] Unexpected exception in WsClient Exception: java.net.UnknownHostException: realtime.ably.io


[Ably internal] No activity for 25000ms, closing connection

...

Error sending request <redacted> to ably. io.ably.lib.types.AblyException: org.java_websocket.exceptions.WebsocketNotConnectedException
```

It looks from `WebsocketNotConnectedException` that the `ConnectionManager` is still attempting to send on a closed connection.

**Comment by paddybyers** [comment]
Related (internal):
https://support.ably.io/a/tickets/102157
https://app.intercom.io/a/apps/ua39m1ld/inbox/inbox/conversation/23324733872#part_id=comment-23324733872-3592513662

**Comment by tomczoink** [comment]
<div>Agent Tom Camp linked Freshdesk ticket <a href="https://ably.freshdesk.com/a/tickets/102157">102157 </a>for this issue</div>

**Comment by paddybyers** [comment]
Related (internal): https://app.intercom.io/a/apps/ua39m1ld/inbox/inbox/conversation/23402073164#part_id=comment-23402073164-3667214320

```
Found one Java-level deadlock:
=============================
"Timer-3":
  waiting to lock monitor 0x64403278 (object 0x6a70c150, a io.ably.lib.transport.ConnectionManager),
  which is held by "Thread-16"
"Thread-16":
  waiting to lock monitor 0x64402e18 (object 0x6a70c238, a io.ably.lib.realtime.Channel),
  which is held by "Timer-3"

Java stack information for the threads listed above:
===================================================
"Timer-3":
	at io.ably.lib.transport.ConnectionManager.send(ConnectionManager.java:1070)
	- waiting to lock <0x6a70c150> (a io.ably.lib.transport.ConnectionManager)
	at io.ably.lib.realtime.Channel.attachImpl(Channel.java:145)
	at io.ably.lib.realtime.Channel.attachWithTimeout(Channel.java:318)
	- locked <0x6a70c238> (a io.ably.lib.realtime.Channel)
	at io.ably.lib.realtime.Channel.access$700(Channel.java:25)
	at io.ably.lib.realtime.Channel$3.run(Channel.java:385)
	- locked <0x6a70c238> (a io.ably.lib.realtime.Channel)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
"Thread-16":
	at io.ably.lib.realtime.Channel.setSuspended(Channel.java:502)
	- waiting to lock <0x6a70c238> (a io.ably.lib.realtime.Channel)
	at io.ably.lib.transport.ConnectionManager.setState(ConnectionManager.java:296)
	at io.ably.lib.transport.ConnectionManager.handleStateChange(ConnectionManager.java:779)
	at io.ably.lib.transport.ConnectionManager.notifyState(ConnectionManager.java:329)
	- locked <0x6a70c150> (a io.ably.lib.transport.ConnectionManager)
	at io.ably.lib.transport.ConnectionManager.onTransportUnavailable(ConnectionManager.java:948)
	- locked <0x6a70c150> (a io.ably.lib.transport.ConnectionManager)
	at io.ably.lib.transport.WebSocketTransport.connect(WebSocketTransport.java:82)
	at io.ably.lib.transport.ConnectionManager.connectImpl(ConnectionManager.java:997)
	at io.ably.lib.transport.ConnectionManager.handleStateRequest(ConnectionManager.java:697)
	at io.ably.lib.transport.ConnectionManager.access$800(ConnectionManager.java:24)
	at io.ably.lib.transport.ConnectionManager$CMThread.run(ConnectionManager.java:865)
	- locked <0x6a70c150> (a io.ably.lib.transport.ConnectionManager)

Found 1 deadlock.
```

**Comment by paddybyers** [comment]
After the 1.1.4 changes, there still seems to be an issue:

```
Found one Java-level deadlock:
=============================
"Timer-7":
  waiting to lock monitor 0x005ef798 (object 0x6a9b3b08, a org.java_websocket.WebSocketImpl),
  which is held by "WebSocketConnectReadThread-10352"
"WebSocketConnectReadThread-10352":
  waiting to lock monitor 0x005ee8b8 (object 0x6a9b3bc0, a io.ably.lib.transport.WebSocketTransport),
  which is held by "Thread-16"
"Thread-16":
  waiting to lock monitor 0x005ef798 (object 0x6a9b3b08, a org.java_websocket.WebSocketImpl),
  which is held by "WebSocketConnectReadThread-10352"

Java stack information for the threads listed above:
===================================================
"Timer-7":
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:477)
	- waiting to lock <0x6a9b3b08> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:526)
	at org.java_websocket.client.WebSocketClient.closeConnection(WebSocketClient.java:731)
	at io.ably.lib.transport.WebSocketTransport$WsClient.checkActivity(WebSocketTransport.java:312)
	at io.ably.lib.transport.WebSocketTransport$WsClient.access$500(WebSocketTransport.java:151)
	at io.ably.lib.transport.WebSocketTransport$WsClient$WsClientTimerTask.run(WebSocketTransport.java:328)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
"WebSocketConnectReadThread-10352":
	at io.ably.lib.transport.WebSocketTransport$WsClient.onClose(WebSocketTransport.java:243)
	- waiting to lock <0x6a9b3bc0> (a io.ably.lib.transport.WebSocketTransport)
	at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:493)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:504)
	- locked <0x6a9b3b08> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:554)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:391)
	at java.lang.Thread.run(Thread.java:748)
"Thread-16":
	at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:416)
	- waiting to lock <0x6a9b3b08> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:569)
	at org.java_websocket.client.WebSocketClient.close(WebSocketClient.java:290)
	at io.ably.lib.transport.WebSocketTransport.close(WebSocketTransport.java:103)
	- locked <0x6a9b3bc0> (a io.ably.lib.transport.WebSocketTransport)
	at io.ably.lib.transport.ConnectionManager.handleStateRequest(ConnectionManager.java:691)
	at io.ably.lib.transport.ConnectionManager.access$1000(ConnectionManager.java:26)
	at io.ably.lib.transport.ConnectionManager$CMThread.run(ConnectionManager.java:863)
	- locked <0x6a67e7e8> (a io.ably.lib.transport.ConnectionManager)

Found 1 deadlock.

```

@amsurana are you able to have a look please?

**Comment by paddybyers** [comment]
Another deadlock, on 1.1.5 this time:

```
Found one Java-level deadlock:
=============================
"Timer-19":
  waiting to lock monitor 0x0078cf30 (object 0x6ab44b98, a org.java_websocket.WebSocketImpl),
  which is held by "WebSocketConnectReadThread-219589"
"WebSocketConnectReadThread-219589":
  waiting to lock monitor 0x6450e418 (object 0x6a75d7e0, a io.ably.lib.transport.ConnectionManager),
  which is held by "Thread-21"
"Thread-21":
  waiting to lock monitor 0x0078cf30 (object 0x6ab44b98, a org.java_websocket.WebSocketImpl),
  which is held by "WebSocketConnectReadThread-219589"

Java stack information for the threads listed above:
===================================================
"Timer-19":
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:477)
	- waiting to lock <0x6ab44b98> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:526)
	at org.java_websocket.client.WebSocketClient.closeConnection(WebSocketClient.java:731)
	at io.ably.lib.transport.WebSocketTransport$WsClient.checkActivity(WebSocketTransport.java:309)
	at io.ably.lib.transport.WebSocketTransport$WsClient.access$400(WebSocketTransport.java:151)
	at io.ably.lib.transport.WebSocketTransport$WsClient$WsClientTimerTask.run(WebSocketTransport.java:325)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
"WebSocketConnectReadThread-219589":
	at io.ably.lib.transport.ConnectionManager.onTransportUnavailable(ConnectionManager.java:932)
	- waiting to lock <0x6a75d7e0> (a io.ably.lib.transport.ConnectionManager)
	at io.ably.lib.transport.WebSocketTransport$WsClient.onClose(WebSocketTransport.java:242)
	at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:493)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:504)
	- locked <0x6ab44b98> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:554)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:391)
	at java.lang.Thread.run(Thread.java:748)
"Thread-21":
	at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:416)
	- waiting to lock <0x6ab44b98> (a org.java_websocket.WebSocketImpl)
	at org.java_websocket.WebSocketImpl.close(WebSocketImpl.java:569)
	at org.java_websocket.client.WebSocketClient.close(WebSocketClient.java:290)
	at io.ably.lib.transport.WebSocketTransport.close(WebSocketTransport.java:103)
	- locked <0x6ab44dc8> (a io.ably.lib.transport.WebSocketTransport)
	at io.ably.lib.transport.ConnectionManager.handleStateRequest(ConnectionManager.java:691)
	at io.ably.lib.transport.ConnectionManager.access$1000(ConnectionManager.java:26)
	at io.ably.lib.transport.ConnectionManager$CMThread.run(ConnectionManager.java:863)
	- locked <0x6a75d7e0> (a io.ably.lib.transport.ConnectionManager)

Found 1 deadlock.
```

This is different, in that thelocks in question are the `ConnectionManager` lock and a lock that's internal to the underlying websocket library.

It would have been better if the underlying library didn't hold its lock whilst delivering an `onClose` event, but there we are. The handler for the closing of the transport requires synchronous access to the `ConnectionManager` state to check, for example, that the transport that generated the event is actually the current transport.

So I think there are two possible approaches to address this:

- a localised change to `WebSocketTransport`, where a task runs in response to each callback from the client, so no library code runs in the context of the wsclient event callbacks;

- a change to `ConnectionManager` where there is an explicit queue of events needing to be handled by the CM thread, and entrypoints such as `onTransportUnavailable()` push to that queue (synchronised on a lock that is local to the queue), and those queued events are handled in the CM `run()` loop.

**Comment by paddybyers** [comment]
After the 1.1.6 changes, we have yet a different manifestation of this problem.

What's happening is that the transport is closing, and in `WsClient.onClose()` we are notified synchronously of this, but now that state change is propagated asynchronously to the `ConnectionManager`. This means that any intervening request on the `WsClient` - eg to `send()` - fails because the socket is disconnected.

Simply catching the exception isn't enough - since the socket is disconnected, the library should be queueing the message (so it can be sent later) instead of attempting to send it.

So ISTM that we do have to find a way to reinstate a synchronous update to the `ConnectionManager` state, without deadlocking because of lock acquisition order problems.
