### ISSUE TITLE
Host fallback for REST

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#54]
It's possible our host fallback is not working correctly following a chat with a customer who is experiencing issues.  They have confirmed at the time they are unable to curl to rest.ably.io, however I would then expect the client to route to a different data centre.

See error below:

```
2015-12-03 08:10:02.905 ERROR 11292 --- [       Timer-26] messaging.MessengerImpl                  : Connection failed; no host available
io.ably.types.AblyException: Connection failed; no host available
	at io.ably.http.Http.post(Unknown Source)
	at io.ably.rest.Channel.publish(Unknown Source)
	at messaging.AblyMessagingRestImpl.sendMessage(AblyMessagingRestImpl.java:31)
	at demo.SchedulerCallable.sendLocationMessage(SchedulerCallable.java:186)
	at demo.SchedulerCallable.process(SchedulerCallable.java:51)
	at demo.SchedulerCallable$1.run(SchedulerCallable.java:80)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
.(INFO): io.ably.rest.AblyRest: started
(INFO): Auth(): anonymous, using basic auth
```

**Comment by mattheworiordan** [comment]
Related to https://github.com/ably/ably-java/issues/14
