### ISSUE TITLE
ConnectionManager.checkConnectivity() fails every time for Android 9

### ISSUE THREAD

**Issue by jrileydev** [ably/ably-java#541]
ConnectionManager uses an [HTTP url](https://github.com/ably/ably-java/blob/develop/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L42) to check network connectivity.  However, on Android 9 the default network security policy [does not permit cleartext network requests](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted) and throws the following exception for every call to `checkConnectivity()`

> 2019-12-15 05:06:52.744 16966-17105/com.eturi.ourpactjr W/System.err: java.io.IOException: Cleartext HTTP traffic to internet-up.ably-realtime.com not permitted
2019-12-15 05:06:52.745 16966-17105/com.eturi.ourpactjr W/System.err:     at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
2019-12-15 05:06:52.746 16966-17105/com.eturi.ourpactjr W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
2019-12-15 05:06:52.746 16966-17105/com.eturi.ourpactjr W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
2019-12-15 05:06:52.746 16966-17105/com.eturi.ourpactjr W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
2019-12-15 05:06:52.746 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.http.HttpCore.readResponse(HttpCore.java:392)
2019-12-15 05:06:52.747 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.http.HttpCore.httpExecute(HttpCore.java:249)
2019-12-15 05:16:54.081 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.http.HttpCore.httpExecute(HttpCore.java:156)
2019-12-15 05:16:54.081 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.http.HttpCore.httpExecuteWithRetry(HttpCore.java:74)
2019-12-15 05:16:54.082 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.http.HttpHelpers.httpExecute(HttpHelpers.java:107)
2019-12-15 05:16:54.082 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.http.HttpHelpers.getUrl(HttpHelpers.java:56)
2019-12-15 05:16:54.082 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.http.HttpHelpers.getUrlString(HttpHelpers.java:44)
2019-12-15 05:16:54.082 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.transport.ConnectionManager.checkConnectivity(ConnectionManager.java:1035)
2019-12-15 05:16:54.083 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.transport.ConnectionManager.checkSuspend(ConnectionManager.java:796)
2019-12-15 05:16:54.083 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.transport.ConnectionManager.access$1200(ConnectionManager.java:26)
2019-12-15 05:16:54.083 16966-17105/com.eturi.ourpactjr W/System.err:     at io.ably.lib.transport.ConnectionManager$CMThread.run(ConnectionManager.java:875)

Would it possible to change the url to HTTPS?

**Comment by paddybyers** [comment]
> Would it possible to change the url to HTTPS?

Yes, we'll fix this asap. Thanks for the information.
