### ISSUE TITLE
Potential breaking change in android-java v1.2.3

### ISSUE THREAD

**Issue by markcoxsmith** [ably/ably-java#638]
**Message from customer**

I have tried to run the application just by changing the version. Below is the code for it.
Once we received the fcm token, registerAblyPn function was called.
```
74    private fun registerAblyPn(token: String) {
75        val ablyContext = ActivationContext.getActivationContext(appContext)
76        ablyContext.onNewRegistrationToken(RegistrationToken.Type.FCM, token)
77        deviceToken = token
78        ablyDeviceId = ablyContext.localDevice.id
79    }
```
Below is the error message.
```
12-15 03:24:55.406 20211 20211 D [NATIVE]com.example.digital_banking_app.utils.FirebaseUtil: Registration for remote notifications successful. Token: <redacted>on:<redacted>
12-15 03:24:55.436 20406 20406 I Perf  : Connecting to perf service.
12-15 03:24:55.436 20211 20211 D AndroidRuntime: Shutting down VM
12-15 03:24:55.437 20211 20211 E AndroidRuntime: FATAL EXCEPTION: main
12-15 03:24:55.437 20211 20211 E AndroidRuntime: Process: com.jago.digitalBankingApp_dev, PID: 20211
12-15 03:24:55.437 20211 20211 E AndroidRuntime: java.lang.IllegalStateException: ablyContext.localDevice.id must not be null
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at com.example.digital_banking_app.services.AblyChannelService.registerAblyPn(AblyChannelService.kt:78)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at com.example.digital_banking_app.services.AblyChannelService.access$registerAblyPn(AblyChannelService.kt:26)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at com.example.digital_banking_app.services.AblyChannelService$setUpAbly$2.getToken(AblyChannelService.kt:66)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at com.example.digital_banking_app.utils.FirebaseUtil$getFirebaseToken$1.onComplete(FirebaseUtil.kt:28)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:883)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:100)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at android.os.Looper.loop(Looper.java:214)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7710)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
12-15 03:24:55.437 20211 20211 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
Couldn't proceed to test the actual issue.
Is there a breaking change in the ably 1.2.3 version ?

**Comment by sacOO7** [comment]
Might be related to #623

**Comment by sacOO7** [comment]
It will be great if we can get verbose logging (along with above error), that way it's easy to trace the exact error.
Currently, the verbose logging is not enabled.

**Comment by QuintinWillison** [comment]
This has been resolved at the customer's side.
