### ISSUE TITLE
Android 4.2.2 cannot connect anymore

### ISSUE THREAD

**Issue by monossido** [ably/ably-java#666]
(I've also reported this issue to Ably support, I don't know if it's just someting temporary with the server or if there is something related to this library anyway)

Suddenly from day to day my Android 4.2.2 clients cannot connect to ably. The clients is using an old version of this library, but I've tried also the last one.

There is some log with verbose option

```
(VERBOSE): io.ably.lib.transport.ConnectionManager: requestState(): requesting connecting; id = null
(VERBOSE): io.ably.lib.transport.ConnectionManager: setState(): setting connecting; reason null
<ably> connection state is connecting
(DEBUG): io.ably.lib.transport.WebSocketTransport: close()
(INFO): Auth.assertValidToken(): 
(INFO): Auth.assertValidToken(): using cached token; expires = 0
(INFO): TokenAuth.getTokenDetails(): 
(DEBUG): io.ably.lib.transport.ITransport: getConnectParams: params = [accessToken:ogK5AQ.F8loazclrlU8UIwvLZNGYpkmfsljDGu7QXaQb1RhcCaQ2PfpJGYoEiVNliDTvyRWh8-z3a2ZnYOkqL7Bsxcv6WTNa2uU2kSKxwbOM-yHiEXAYUAcL_gnRwZTOF6rg3UGqETAPWhY4qBYC1TOpGtZ5P5_6iZkbsvec9l2eCj-a6bw, v:1.2, format:msgpack, clientId:3BTCGKGR, heartbeats:false, lib:android-1.2.5]
(DEBUG): io.ably.lib.transport.WebSocketTransport: connect(); wsUri = wss://realtime.ably.io:443/?accessToken=ogK5AQ.F8loazclrlU8UIwvLZNGYpkmfsljDGu7QXaQb1RhcCaQ2PfpJGYoEiVNliDTvyRWh8-z3a2ZnYOkqL7Bsxcv6WTNa2uU2kSKxwbOM-yHiEXAYUAcL_gnRwZTOF6rg3UGqETAPWhY4qBYC1TOpGtZ5P5_6iZkbsvec9l2eCj-a6bw&v=1.2&format=msgpack&clientId=3BTCGKGR&heartbeats=false&lib=android-1.2.5
(ERROR): io.ably.lib.transport.WebSocketTransport: Connection error 
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8402010: Failure in SSL library, usually a protocol error
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (external/openssl/ssl/s23_clnt.c:766 0xa8d5d5e1:0x00000000)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:420)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:636)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:607)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:407)
    at java.lang.Thread.run(Thread.java:856)
    Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8402010: Failure in SSL library, usually a protocol error
    error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (external/openssl/ssl/s23_clnt.c:766 0xa8d5d5e1:0x00000000)
    at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:378)
	... 4 more
(VERBOSE): io.ably.lib.http.HttpCore: HTTP request: https://internet-up.ably-realtime.com/is-the-internet-up.txt GET
(VERBOSE): io.ably.lib.http.HttpCore:   Accept: application/json
(VERBOSE): io.ably.lib.http.HttpCore:   X-Ably-Lib: android-1.2.5
(VERBOSE): io.ably.lib.http.HttpCore:   X-Ably-Version: 1.2
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8402010: Failure in SSL library, usually a protocol error
error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0xa8d5d5e1:0x00000000)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:420)
    at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282)
    at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:495)
    at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
    at io.ably.lib.http.HttpCore.readResponse(HttpCore.java:398)
    at io.ably.lib.http.HttpCore.httpExecute(HttpCore.java:255)
    at io.ably.lib.http.HttpCore.httpExecute(HttpCore.java:162)
    at io.ably.lib.http.HttpCore.httpExecuteWithRetry(HttpCore.java:80)
    at io.ably.lib.http.HttpHelpers.httpExecute(HttpHelpers.java:108)
    at io.ably.lib.http.HttpHelpers.getUrl(HttpHelpers.java:57)
    at io.ably.lib.http.HttpHelpers.getUrlString(HttpHelpers.java:45)
    at io.ably.lib.transport.ConnectionManager.checkConnectivity(ConnectionManager.java:1410)
    at io.ably.lib.transport.ConnectionManager.checkFallback(ConnectionManager.java:1219)
    at io.ably.lib.transport.ConnectionManager.onTransportUnavailable(ConnectionManager.java:1295)
    at io.ably.lib.transport.WebSocketTransport$WsClient.onError(WebSocketTransport.java:227)
    at org.java_websocket.client.WebSocketClient.onWebsocketError(WebSocketClient.java:536)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:412)
    at java.lang.Thread.run(Thread.java:856)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8402010: Failure in SSL library, usually a protocol error
error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0xa8d5d5e1:0x00000000)
    at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:378)
    ... 22 more
(VERBOSE): io.ably.lib.transport.ConnectionManager: checkSuspended: timeToSuspend = -482389ms; suspendMode = true
(VERBOSE): io.ably.lib.transport.ConnectionManager: setState(): setting suspended; reason [ErrorInfo message=javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8402010: Failure in SSL library, usually a protocol error
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (external/openssl/ssl/s23_clnt.c:766 0xa8d5d5e1:0x00000000) (See https://help.ably.io/error/80000) code=80000 statusCode=503 href=https://help.ably.io/error/80000]
(DEBUG): io.ably.lib.transport.WebSocketTransport: onClose(): wsCode = -1; wsReason = javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8402010: Failure in SSL library, usually a protocol error
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (external/openssl/ssl/s23_clnt.c:766 0xa8d5d5e1:0x00000000); remote = false
(DEBUG): io.ably.lib.transport.ConnectionManager: Wait ended by action: io.ably.lib.transport.ConnectionManager$SynchronousStateChangeAction@ae8f1ef8
<ably> connection state is suspended
(VERBOSE): io.ably.lib.transport.ConnectionManager: checkSuspended: timeToSuspend = -482390ms; suspendMode = true
(VERBOSE): io.ably.lib.transport.ConnectionManager: setState(): not transitioning; not a valid transition suspended
(DEBUG): io.ably.lib.transport.ConnectionManager: Wait ended by action: io.ably.lib.transport.ConnectionManager$SynchronousStateChangeAction@ae8f27a8

```

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-699) by [Unito](https://www.unito.io/learn-more)

**Comment by paddybyers** [comment]
Hi. Thanks for reporting this issue.

Yes, I believe this is related to a problem we've had today, where our AWS CloudFront endpoint is no longer handling non-SNI-capable clients. We're working to resolve it.

**Comment by monossido** [comment]
I't s big problem for us at the moment, the support is not responding anymore.
If you have some news please tell me.

Thank you.

**Comment by paddybyers** [comment]
> the support is not responding anymore

@monossido I'm not sure what you mean - please respond directly to support@ably.com so we can connect with you

**Comment by monossido** [comment]
> > the support is not responding anymore
> 
> @monossido I'm not sure what you mean - please respond directly to [support@ably.com](mailto:support@ably.com) so we can connect with you

Already opened a ticket, number 376235169
(sorry for my poor english, yesterday was an hard day)

**Comment by paddybyers** [comment]
@monossido can you check again pls?

**Comment by monossido** [comment]
Solved, thank you!
So, should I upgrade the library and/or provides some new ClientOptions in order to prevent future issues?

**Comment by paddybyers** [comment]
> should I upgrade the library

yes, it's always a good idea to upgrade when there is a new release

> or provides some new ClientOptions in order to prevent future issues?

No, there's nothing specifically related this problem

**Comment by QuintinWillison** [comment]
Thanks both. I'll close this issue but please feel free to re-open or raise a new one if problems persist.
