### ISSUE TITLE
Restore failing test `NotActivated_on_CalledActivate_with_DeviceToken`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#739]
We're consistently getting:

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
at java.lang.Object.wait(Native Method)
at io.ably.lib.test.common.Helpers$AsyncWaiter.waitFor(Helpers.java:775)
at io.ably.lib.test.android.AndroidPushTest$1TestCase.run(AndroidPushTest.java:584)
at io.ably.lib.test.util.TestCases$1.apply(TestCases.java:28)
at io.ably.lib.test.util.TestCases$1.apply(TestCases.java:24)
at io.ably.lib.test.common.Helpers.expectedError(Helpers.java:77)
at io.ably.lib.test.util.TestCases.run(TestCases.java:24)
at io.ably.lib.test.android.AndroidPushTest.NotActivated_on_CalledActivate_with_DeviceToken(AndroidPushTest.java:695)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by QuintinWillison** [comment]
Disabled in #738
