### ISSUE TITLE
Presence data assumed to be a string, Map not supported

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#75]
Background:

> I think the Java lib either handles presence messages badly, or I'm not doing something correctly when a user in the Cordova app sends a presence message (`{isTyping: true}`), the java lib throws an exception
> http://pastebin.com/HaTTKKxg
> also, if I pass a `Map<string, boolean>` to `sessionChannel.presence.update()`, when it comes back, the `presenceMessage.data` in a `PresenceListener` is a `string`, instead of the `Map<string, boolean>` I sent

We need to ensure the Java lib can accept all the accepted data types (String, Binary, Map/Hash) in presence data and also set data with all these data types.

**Comment by stannedelchev** [comment]
@paddybyers Here are some hex dumps, generated via `ably-java/lib/src/main/java/io/ably/lib/transport/WebSocketTransport.java`:

	public String bytesToHex(byte[] bytes) {
		char[] hexArray = "0123456789ABCDEF".toCharArray();
	    char[] hexChars = new char[bytes.length * 2];
	    for ( int j = 0; j < bytes.length; j++ ) {
	        int v = bytes[j] & 0xFF;
	        hexChars[j * 2] = hexArray[v >>> 4];
	        hexChars[j * 2 + 1] = hexArray[v & 0x0F];
	    }
	    return new String(hexChars);
	}

	@Override
	public void onMessage(ByteBuffer blob) {
		try {
			Log.v("", bytesToHex(blob.array()));
			connectionManager.onMessage(ProtocolSerializer.readMsgpack(blob.array()));
			Log.v("", "on msg success");
		} catch (AblyException e) {
			String msg = "Unexpected exception processing received binary message";
			Log.e(TAG, msg, e);
		}
	}


```
01-14 22:50:47.190 (VERBOSE): 89A6616374696F6E0EA26964AD43743332465F6F5A382D2D3133A5636F756E740FA76368616E6E656CAB6D6F62696C653A63686174AD6368616E6E656C53657269616CB0623962623533363539333031363A3335AC636F6E6E656374696F6E4964AA43743332465F6F5A382DB0636F6E6E656374696F6E53657269616C04A974696D657374616D70CF0000015241E8E4E6A870726573656E63659184A8636C69656E744964A5636F726469AC636F6E6E656374696F6E4964AA43743332465F6F5A382DA6616374696F6E04A46461746181A86973547970696E67C3
01-14 22:50:47.190 (ERROR): io.ably.lib.transport.WebSocketTransport: Unexpected exception in WsClient
01-14 22:50:47.190 org.msgpack.core.MessageTypeException: Expected String, but got Map (81)
01-14 22:50:47.190 at org.msgpack.core.MessageUnpacker.unexpected(MessageUnpacker.java:535)
01-14 22:50:47.190 at org.msgpack.core.MessageUnpacker.unpackRawStringHeader(MessageUnpacker.java:1126)
01-14 22:50:47.190 at org.msgpack.core.MessageUnpacker.unpackString(MessageUnpacker.java:952)
01-14 22:50:47.190 at io.ably.lib.types.BaseMessage.readField(BaseMessage.java:176)
01-14 22:50:47.190 at io.ably.lib.types.PresenceMessage.readMsgpack(PresenceMessage.java:108)
01-14 22:50:47.190 at io.ably.lib.types.PresenceMessage.fromMsgpack(PresenceMessage.java:120)
01-14 22:50:47.190 at io.ably.lib.types.PresenceSerializer.readMsgpackArray(PresenceSerializer.java:30)
01-14 22:50:47.190 at io.ably.lib.types.ProtocolMessage.readMsgpack(ProtocolMessage.java:181)
01-14 22:50:47.190 at io.ably.lib.types.ProtocolMessage.fromMsgpack(ProtocolMessage.java:193)
01-14 22:50:47.190 at io.ably.lib.types.ProtocolSerializer.readMsgpack(ProtocolSerializer.java:21)
01-14 22:50:47.190 at io.ably.lib.transport.WebSocketTransport$WsClient.onMessage(WebSocketTransport.java:160)
01-14 22:50:47.190 at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:253)
01-14 22:50:47.190 at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381)
01-14 22:50:47.190 at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
01-14 22:50:47.190 at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
01-14 22:50:47.190 at java.lang.Thread.run(Thread.java:818)
01-14 22:50:50.210 (VERBOSE): 81A6616374696F6E00
01-14 22:50:50.210 (VERBOSE): on msg success
01-14 22:50:52.810 (VERBOSE): 89A6616374696F6E0EA26964AD43743332465F6F5A382D2D3134A5636F756E740FA76368616E6E656CAB6D6F62696C653A63686174AD6368616E6E656C53657269616CB0623962623533363539333031363A3336AC636F6E6E656374696F6E4964AA43743332465F6F5A382DB0636F6E6E656374696F6E53657269616C05A974696D657374616D70CF0000015241E8FB32A870726573656E63659184A8636C69656E744964A5636F726469AC636F6E6E656374696F6E4964AA43743332465F6F5A382DA6616374696F6E04A46461746181A86973547970696E67C2
01-14 22:50:52.810 (ERROR): io.ably.lib.transport.WebSocketTransport: Unexpected exception in WsClient
01-14 22:50:52.810 org.msgpack.core.MessageTypeException: Expected String, but got Map (81)
01-14 22:50:52.810 at org.msgpack.core.MessageUnpacker.unexpected(MessageUnpacker.java:535)
01-14 22:50:52.810 at org.msgpack.core.MessageUnpacker.unpackRawStringHeader(MessageUnpacker.java:1126)
01-14 22:50:52.810 at org.msgpack.core.MessageUnpacker.unpackString(MessageUnpacker.java:952)
01-14 22:50:52.810 at io.ably.lib.types.BaseMessage.readField(BaseMessage.java:176)
01-14 22:50:52.810 at io.ably.lib.types.PresenceMessage.readMsgpack(PresenceMessage.java:108)
01-14 22:50:52.810 at io.ably.lib.types.PresenceMessage.fromMsgpack(PresenceMessage.java:120)
01-14 22:50:52.810 at io.ably.lib.types.PresenceSerializer.readMsgpackArray(PresenceSerializer.java:30)
01-14 22:50:52.810 at io.ably.lib.types.ProtocolMessage.readMsgpack(ProtocolMessage.java:181)
01-14 22:50:52.810 at io.ably.lib.types.ProtocolMessage.fromMsgpack(ProtocolMessage.java:193)
01-14 22:50:52.810 at io.ably.lib.types.ProtocolSerializer.readMsgpack(ProtocolSerializer.java:21)
01-14 22:50:52.810 at io.ably.lib.transport.WebSocketTransport$WsClient.onMessage(WebSocketTransport.java:160)
01-14 22:50:52.810 at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:253)
01-14 22:50:52.810 at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381)
01-14 22:50:52.810 at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
01-14 22:50:52.810 at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
01-14 22:50:52.810 at java.lang.Thread.run(Thread.java:818)
```

**Comment by mattheworiordan** [comment]
Thanks @stannedelchev, any idea @paddybyers?  Should we get @gokhanbarisaker to look at this as a priority?

**Comment by paddybyers** [comment]
The final bytes of the first dumped message:

    A46461746181A86973547970696E67C3

Compare with:

````
> msgpack.encode({data:{isTyping: true}})
<Buffer 81 a4 64 61 74 61 81 a8 69 73 54 79 70 69 6e 67 c3>
````

So clearly the structure that was packed is invalid, because the `data` member, when packed (ie after encoding) may only be a string or a buffer (msgpack `BIN`).

So the sender of this message is the problem because instead of packing a message like:

````
{
  data: {
    isTyping: true
  }
}
````

it should be:

````
{
  data: '{"isTyping": true}',
  encoding: 'json'
}
````

The `encode()` step has been skipped. Which library is being used to send?

**Comment by stannedelchev** [comment]
the JS lib sends the message from the Cordova demo app hosted on heroku

**Comment by paddybyers** [comment]
> the JS lib sends the message from the Cordova demo app hosted on heroku

One for @SimonWoolf ?

**Comment by mattheworiordan** [comment]
@stannedelchev, perhaps so that you are not blocked, simply disable the binary protocol for both client libraries, you can do this easily with `useBinaryProtocol: false`, see http://docs.ably.io/client-lib-development-guide/features/#TO3f
