### ISSUE TITLE
`auth_renewAuth_callback_invoked` test failing with `AssertionError` "Callback not invoked"

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#863]
From [this test run](https://github.com/ably/ably-java/actions/runs/3532982505/jobs/5929397279#step:3:885):

```
io.ably.lib.test.realtime.RealtimeAuthTest > auth_renewAuth_callback_invoked[binary_protocol] FAILED
    java.lang.AssertionError: Callback not invoked
```

As discussed in [this Slack thread (internal)](https://ably-real-time.slack.com/archives/C019LDWM9UH/p1669218490931509) this test was added in https://github.com/ably/ably-java/pull/825 and a working theory is that this might be a regression as a result of the `1.2` to `1.1` protocol downgrade in https://github.com/ably/ably-java/pull/858.

**Comment by QuintinWillison** [comment]
Seen to fail [here](https://github.com/ably/ably-java/actions/runs/3854323429/jobs/6574733842#step:3:528):

```
io.ably.lib.test.realtime.RealtimeSuite > io.ably.lib.test.realtime.RealtimeAuthTest.auth_renewAuth_callback_invoked[binary_protocol] FAILED
    java.lang.AssertionError: Callback not invoked
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.ably.lib.test.realtime.RealtimeAuthTest.auth_renewAuth_callback_invoked(RealtimeAuthTest.java:1121)
```
