### ISSUE TITLE
Long-lived connections are immediately transitioned to `SUSPENDED` after disconnection

### ISSUE THREAD

**Issue by AndyTWF** [ably/ably-java#925]
Relates to spec:

- `DF1a`
- `RTN14d`
- `RTN15g`

The default `connectionStateTtl` value (how long the connection is persisted on the Ably servers) is 120 seconds. This means that after 120 seconds of being `DISCONNECTED`, the connection state should transition to `SUSPENDED`.

We maintain a timer (`ConnectionManager.suspendTime`) in `ably-java` that represents the time at which suspension should occur. This is checked whenever:

- A `CONNECTING` state times out
- The transport is unavailable

If the time is not exceeded, the state is transitioned to `DISCONNECTED`. If it is exceeded, then the state becomes `SUSPENDED`.

The `suspendTime` is reset (to `now + connetionStateTtl`) only:

- On `ConnectionManager` initialisation
- On successful connection
- When a `DISCONNECTED` state is enacted, the previous state was `CONNECTED` and immediate retries are not suppressed.

If the only thing a connection has done is successfully connect... and transport becomes unavailable (via connection rebalancing, internet issues etc)... and we've been connected for >`connectionStateTtl`... then `ConnectionManager.onTransportUnavailable` will check the timer, see that it has passed, and immediately suspend the connection.

The correct behaviour here is to enter a `DISCONNECTED` state and immediately retry connections, only suspending at `disconnectTime + connectionStateTtl`.

**Comment by paddybyers** [comment]
I'm not following how this is broken. If there is a state transition, and the previous state was `connected`, then that's the point at which we recalculate the suspend time: https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L313

What's not working?

**Comment by AndyTWF** [comment]
> I'm not following how this is broken. If there is a state transition, and the previous state was `connected`, then that's the point at which we recalculate the suspend time: https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L313
> 
> What's not working?

Assuming that we're happily connected at the time:

When the connection dies for whatever reason, we end up straight in `ConnectionManager.onTransportUnavailable` via `WebsocketTransport.onError` - there are no state transitions queued at this point. On ConnectionManager line 1488 we call checkSuspended, which checks the suspend timer.

If we're connected < 2 minutes (from setSuspendTime call in `onConnected` will be connection timestamp + connection TTL), `checkSuspended` returns a transition to `disconnected`, which then resets the suspend timer (line 313, as you indicate above) and we go through the standard reconnection procedure.

If we've been connected for > 2 minutes, the timer set by the `onConnected` call will have elapsed, and therefore `checkSuspended` returns a transition to `suspended`.

The reason we aren't saved by the timer reset in the `disconnected` state transition is because we never enter that state in this scenario.

**Comment by AndyTWF** [comment]
Some logs from AAT Android to illustrate :)

```
17-03-23 10:56:35.379: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
17-03-23 10:56:50.378: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
17-03-23 10:57:05.378: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
17-03-23 10:57:20.375: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
17-03-23 10:57:35.378: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
17-03-23 10:57:50.474: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
17-03-23 10:58:05.427: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
17-03-23 10:58:20.376: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
17-03-23 10:58:27.004: io.ably.lib.transport.WebSocketTransport: Connection error 
    javax.net.ssl.SSLException: Read error: ssl=0x7b374ea208: I/O error during system call, Software caused connection abort
    	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
    	at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
    	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
    	at java.io.InputStream.read(InputStream.java:101)
    	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:515)
    	at java.lang.Thread.run(Thread.java:919)
17-03-23 10:58:27.009: io.ably.lib.http.HttpCore: HTTP request: https://internet-up.ably-realtime.com/is-the-internet-up.txt GET
17-03-23 10:58:27.010: io.ably.lib.http.HttpCore:   Ably-Agent: ably-java/1.2.26 ably-asset-tracking-android/1.6.4 android/29
17-03-23 10:58:27.011: io.ably.lib.http.HttpCore:   Accept: application/json
17-03-23 10:58:27.011: io.ably.lib.http.HttpCore:   X-Ably-Version: 1.0
17-03-23 10:58:27.036: io.ably.lib.transport.ConnectionManager: checkSuspended: timeToSuspend = -6599ms; suspendMode = true
17-03-23 10:58:27.036: io.ably.lib.transport.ConnectionManager: setState(): setting suspended; reason {ErrorInfo message=Read error: ssl=0x7b374ea208: I/O error during system call, Software caused connection abort (See https://help.ably.io/error/80000) code=80000 statusCode=503 href=https://help.ably.io/error/80000}
17-03-23 10:58:27.037: io.ably.lib.transport.ConnectionManager: Wait ended by action: io.ably.lib.transport.ConnectionManager$SynchronousStateChangeAction@389300d
17-03-23 10:58:27.039: io.ably.lib.realtime.Channel: setSuspended(); channel = tracking:abc
17-03-23 10:58:27.037: io.ably.lib.transport.WebSocketTransport: onClose(): wsCode = 1006; wsReason = ; remote = true
```
